from mindspore.communication import GlobalComm, get_group_size as get_world_size, get_rank, create_group
from mindspore.mint.distributed import init_process_group, destroy_process_group
from mindspore.communication.comm_func import barrier
from mindspore.communication._comm_helper import _ExistingGroup, _HCCL_TEST_AVAILABLE

_HCCL_TEST_AVAILABLE = True

ProcessGroup = str

def is_initialized():
    return GlobalComm.INITED

def new_group(ranks=None, timeout=None, backend=None, pg_options=None, use_local_synchronization=False, group_desc=None):
    group = str(len(_ExistingGroup.ITEMS))
    create_group(group, list(ranks))
    return group

class Backend:
    class Options:
        def __init__(self, backend: str, timeout = ...) -> None: ...
        @property
        def backend(self) -> str: ...
        @property
        def _timeout(self) -> int: ...
        @_timeout.setter
        def _timeout(self, val) -> None: ...

    def __init__(
        self,
        rank: int,
        size: int,
    ) -> None: ...
    @property
    def supports_splitting(self) -> bool: ...
    @property
    def options(self) -> Options: ...
    def rank(self) -> int: ...
    def size(self) -> int: ...
    def eager_connect_single_device(self, device: None) -> None: ...
    def _set_sequence_number_for_group(self) -> None: ...
    def _set_default_timeout(self, timeout) -> None: ...


class ProcessGroupNCCL(Backend):
    class NCCLConfig:
        blocking: int
        cga_cluster_size: int
        min_ctas: int
        max_ctas: int

    class Options(Backend.Options):
        config: dict
        is_high_priority_stream: bool
        split_from: dict
        split_color: int
        global_ranks_in_group: list[int]
        group_name: str

        def __init__(self, is_high_priority_stream: bool = False): ...

    def __init__(
        self,
        store,
        rank: int,
        size: int,
        options: Options,
    ) -> None: ...
    def _group_start(self) -> None: ...
    def _group_end(self) -> None: ...
    def _set_default_timeout(self, timeout) -> None: ...
    def _shutdown(self) -> None: ...
    def perform_nocolor_split(self, device) -> None: ...
    def register_mem_pool(self, pool) -> None: ...
    def deregister_mem_pool(self, pool) -> None: ...
    def comm_split_count(self) -> int: ...
    def _add_ephemeral_timeout(self, timeout) -> None: ...
    def abort(self) -> None: ...
    def _is_initialized(self) -> bool: ...
    @property
    def uid(self) -> int: ...
    @property
    def options(self) -> Options: ...  # type: ignore[override]
